### ISSUE TITLE
Update RBAC Table

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#1003]
### Description

We have a couple of stories in this release around user levels and their permissions, 
Adding a task to make sure that we update the RBAC table in Docs with the new users and their access levels,

Admin is now a level of user within RBAC having the same access as an Owner EXECPT they are not able to login to node-red

Read Only users, have full read access but no write. (table may need some adjustment to show this)

**Comment by knolleary** [comment]
When I updated the RBAC table around admin permissions, I chose not to add an 'admin' column to the table - as for the vast majority of users on a platform, they have no relationship with the admins of the platform. I chose to add a note to the bottom of the table.

For the viewer role, updating the RBAC table will be delivered as part of that story - #657 

But I do think the content of the table needs updating. It is currently *very* detailed in terms of individual UI components, rather than a summary of the capabilities a user has access to. Useful from a development standpoint, but not suitable (IMHO) for user documentation.

For example, it has `Create Project` listed twice - once for the Overview page and once for the team Projects page - but the information is the same.

I think it needs rationalising to document the capabilities - regardless of where in the UI it is done.
