### ISSUE TITLE
Following email verification link twice throws error

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1024]
### Current Behavior

If you follow an email verification link twice it throws and error.

This is a problem with HotMail users because they follow links in emails before "delivery" so the email address will be pre-verified before the user even sees the email.

This  is likely to break password reset as well  (not checked, but I'm guessing it works in a similar way)

### Expected Behavior

If the address has already been verified, don't show an error, just take them to the login page

### Steps To Reproduce

Sign up to FF cloud with a hotmail email address (other services may do the same)

### Environment

- FlowForge version: 0.9.0
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: K8s/Linux
- Browser: NA

**Comment by sammachin** [comment]
Just thinking if we need to try and do something to mitigate this with hotmail (and others) 
Should the verification page link in the email take you to a page that requires you to click a button to explicitly verify 🤔 
Otherwise there's not really any point in verifying a hotmail address.

This isn't an issue for password reset as the link takes you to a page to set a new password (enter twice and click submit) If you don't complete that form then the link can be loaded multiple times until it expires.

**Comment by hardillb** [comment]
First pass is not show a raw error, how we deal with it long term may need a bit more thinking
