### ISSUE TITLE
How to enable Project settings?

### ISSUE THREAD

**Issue by akashtalole** [flowforge/flowforge#1121]
### Current Behavior

Added below conf for project in setting but project settings are not visible in editor.

`        projects: {
            enabled: true,
            workflow: {
                mode: "manual"
            }
        },
`

### Expected Behavior

It should enable project setting in editor for git. OR provide option to enable project in Templates.

### Steps To Reproduce

add project setting

### Environment

- FlowForge version: 0.10.0
- Node.js version:
- npm version: 
- Platform/OS: Ubuntu 20.04
- Browser: Chrome

**Comment by hardillb** [comment]
Projects are not supported.

Git support and projects are only available when Node-RED is using the default filesystem based storage plugin. FlowForge uses a custom plugin that stores flows/credentials and settings in a central database (because when running on Docker and K8s there is no persistent file system that git could use to save state.)

As we continue to develop FlowForge we will be adding more capability to the version control aspects of flow management. But we currently allow snapshots to be taken and stored which is similar to tagging in git and allow you to roll back to a known good snapshot.

**Comment by knolleary** [comment]
Hi @akashtalole

We do not support the projects feature inside FlowForge due to the way we centralise the storage and management of flows.

We have items in the backlog to provide better version control capability for a the future.

**Comment by akashtalole** [comment]
@hardillb Thanks for update and information on Projects.
