### ISSUE TITLE
Write audit-log events to the standard log as well

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1409]
### Description

We have added audit-logging to lots of places through the code base. That is useful to the admin to know what is going on, however it is only accessible through the frontend.

For some admins, being able to grep a log is also super useful. If we were to also write to the standard log (`app.log.info('something happened')`) at the point we write an entry to the audit log database, we'd instantly get a lot more useful log output of events happening on the platform without having to go back through and add more logging statements.

**Comment by Steve-Mcl** [comment]
@knolleary I have raised PR #1563 

Currently, the audit log entries are added in this format:
![image](https://user-images.githubusercontent.com/44235289/212633288-ee2d607b-acc5-4cda-9510-01c216c7f184.png)

As of writing:
* I did not include the JSON body of the audit log entry 
   * rationale: creates lots of JSON noise & user can look in audit log for details
* I did not try to encode IDs 
   * rationale: not a forward facing "thing"
* log entry format is open to debate (make more parse-able?)

Please advise if you have any suggestions or preferences on the the above & I will get them done asap.  
Otherwise PR can be reviewed/accepted as is.

Ta.

**Comment by Steve-Mcl** [comment]
Verified on local and on staging

Screencap from loki (staging)



![Image](https://user-images.githubusercontent.com/44235289/213192171-5d95fcf4-ebc1-4247-bea4-c113d460f5d4.png)
