### ISSUE TITLE
Re-activation after subscription cancelled

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1422]
### Description

After a teams subscription is cancelled, if they try to add a new project, or start an old one, there's currently no way to re-activate the subscription.

### Epic/Story

#1162

**Comment by Pezmc** [comment]
@joepavitt Do you have any suggestions on a nice way to handle this? Currently the UX looks like the below, which is far from ideal given the billing page also doesn't warn the team that the subscription has expired (see https://github.com/flowforge/flowforge/issues/1421)

<img width="1183" alt="Screenshot 2022-12-14 at 18 04 06" src="https://user-images.githubusercontent.com/507155/207646359-a5ce004c-a735-41d9-816e-a260e59891b6.png">

**Comment by joepavitt** [comment]
Conveniently just opened a PR for better formatting of the errors ,although in this case, it'll still be a little messy when expanded: https://github.com/flowforge/flowforge/pull/1428

**Comment by joepavitt** [comment]
When are the two toast errors fired?

**Comment by joepavitt** [comment]
we could/should also overrides the grid sizing for the audit entires when rendering through Project > Overview.

Currently 

```
.ff-audit-entry {
    grid-template-columns: 75px 50px 1fr 200px;
}
```

Could be:
```.ff-audit-entry {
    grid-template-columns: 75px 50px 1fr 100px;
}

**Comment by Pezmc** [comment]
@joepavitt Sorry was unclear, I'm talking about the wider user experience of handling how to re-activate a teams subscription once it has expired for whatever reason. Currently the only way a team knows their subscription has been expired (other than emails from Stripe) is that trying to start projects fails with the toasts shown in the screenshot. 

I'm going to update the billing page to make it clearer the subscription is cancelled, but still feel like it's a little clunky.

**Comment by joepavitt** [comment]
got it - the billing page is due a revamp (it's never been changed since we rebranded), and I was actually planning on doing some design work on that tomorrow, originally scoped to the new pricing plans ZJ, Nick and I have been discussing, but this is good to factor in too - so may be able to steal some ideas for this sprint, with a bigger overhaul in the future.

Definitely need some indication in the Project Overview that their subscription is no longer valid too, will have a play in Figma now and see what I can come up with. Assume we have an API endpoint that can validate subscription status for a project?
