### ISSUE TITLE
Debugging on Devices

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1703]
### Description

Epic to capture discussion and design conversations around what the developer experience for debugging devices could look like. 

Some initial thoughts were presented here on the overall Dev Experience on Devices (https://github.com/flowforge/flowforge/issues/1012), but this epic will focus particularly on the debugging experience. 

- Can we enable the ability to debug directly in FlowForge,
    - If so, what does that look like?

---

There are three components to look at that are detailed in individual comments below. Two of them we plan to proceed with and have been spun out into their own issues for tracking.

 - https://github.com/flowforge/flowforge/issues/1820
 - https://github.com/flowforge/flowforge/issues/1821

**Comment by joepavitt** [comment]
To be scoped/designed/discussed in 1.5

**Comment by knolleary** [comment]
There are two components to consider when thinking about debugging flows on devices:

1. Node-RED log output
2. Debug node output

They each serve a slightly different purpose, both of which are useful when debugging.

For this comment, I'm focussed on the first one:

### Node-RED log output

We already have a means and method of displaying log output from a node-red instance running inside the platform. We should be able to achieve the same for devices - providing a 'logs' view on the device page. However, we cannot make http requests to gather the logs - instead we need a mechanism to stream the logs over MQTT from the device, and proxy it via a websocket connection to the frontend.

This will only be available for devices connecting to the platform via MQTT. That should be true of all FF Cloud devices as we have the broker properly configured. For self-hosted, the broker remains an optional component, but it does limit the features available if you don't set it up.

1. Device Agent buffers N lines of combined stdout/err history from the Node-RED process.
    - this should include any logging from the device agent as well, in the same way the nr-launcher component does it.
2. The platform can send a command via MQTT to the device to turn on or off log streaming.
    - the device will send its history of messages before starting to send messages live.
3. Due to the overhead involved, we won't automatically stream device logs to the frontend. The device logs page should have a button to start/stop streaming logs. On starting:
   1. opens a websocket connection to the platform to a device logs endpoint
   2. runtime accepts the connection, checks to see if the device is already streaming, if so, sends over its own locally buffered log contents and continues to send log events as they arrive 'live'.
   3. if the device is not currently streaming, the platform sends a command to the device to start streaming - and then forwards anything received over the websocket
   4. When all websockets are closed for a given device, after a short grace period, a command is sent to the device to turn off device streaming.

There's a lot more hidden detail to figure out - topic name spaces, command formats, websocket security, but that is the general shape of how we can expose device logs in the frontend.

**Comment by knolleary** [comment]
Now for part two, accessing the device editor

## Accessing the editor on the device directly

This is the most complicated of all options available. It requires a level of access to the device that will be hard to achieve across networks and boundary firewalls.

The rough shape of it would require some sort of tunnelling proxy to exist between the FF platform and the device. There are commercial solutions that do that sort of thing - ngrok for example.

For our purposes, we could make use of the MQTT broker (as with the logging outline above). I do have reservations about that - it will be pushing a *lot* more data over the shared MQTT broker, alongside all customer data (Project nodes).

I think it would be better to have a dedicated WebSocket connection between the Device Agent and the platform. For an initial iteration, that endpoint can be in the core forge app, but we should build it such that it could be spun out as its own application to avoid overloading the core app.

The basic flow would be:

```mermaid
sequenceDiagram
    autonumber
    User->>FrontEnd: Clicks 'open editor' against device
    FrontEnd->>+Forge: Sends request to create editor session
    Forge--)Device: Publishes command to establish connection
    Device--)Forge: Creates WebSocket connection
    Forge->>-FrontEnd: Returns session identifier
    FrontEnd->>FrontEnd: Opens /device/<id>/editor/
    FrontEnd-->+Forge: Sends requests to /device/<id>/editor/**
    Forge--)+Device: Request proxied over WebSocket
    Device-->>Device: Performs request on local Node-RED
    Device-->>-Forge: Streams response back
    Forge-->>-FrontEnd: Streams response back
    User->>FrontEnd: User navigates away
    FrontEnd-->Forge: Node-RED WebSocket closes
    Note over Forge: if no active WebSockets for this device
    Forge--)Device: Close WebSocket
```

Questions to resolve:

1. Enabling editor on device.
    We currently disable the editor on devices as we specifically don't want it to be accessed. You cannot enable the editor without a restart of Node-RED. That poses a challenge. We could enable the editor listening on localhost only. That would allow our local proxy to access it, but nothing else on the local network.
    We could temporarily enable editor access, on the understanding it requires a restart. Not ideal if trying to debug a 'live' system.

2. Security of Node-RED
    With the editor enabled, even if only listening on localhost, it needs securing properly. Could be achieved by passing a `access_token=<xyz>` query param on the initial load of `index.html`... just a matter of figuring out what that token should be and how/where it is validated.

3. The whole matter of proxying the Browser -> Forge APP HTTP and WebSockets requests over a websocket connection. Some hard work in the details of that for sure.


But stepping back from the technical hows, there is a broader question on whether this is a sensible approach to take at all. What are the consequences of allowing flows to be edited on the device directly? It loses its single source of truth with the platform and will get out of sync with everything else.

That said, if we included a version of nr-tools on the device, the user would be able to develop, snapshot and then push back to the platform. A lot will hinge on how performant the editor experience is when being proxied in this way.

**Comment by knolleary** [comment]
So having said there were two components, I realise I then wrote up something not included in the two I listed. So let's now think about accessing the Debug sidebar.

### Accessing the Debug sidebar content

If we don't go down the path of exposing the whole editor, another option is to provide a custom view of the Debug sidebar messages from the device.

One option could be a custom plugin in the cloud instance of Node-RED that lets the user browse the list of assigned devices, pick one and then see its debug messages in a custom sidebar. This would allow for a lot of code reuse with the existing Debug sidebar and ensure a fairly consistent UX - rather than trying to recreate the Debug sidebar experience within the FF UI. However, there remains some UX issues with this approach.

Thanks to nr-tools, the flows running on a device could be completely different to the flows running in a cloud-hosted instance. That means you don't get the benefit of seeing the device debug messages alongside the flows that generated them. They could be entirely different. That could feel pretty disjointed.

Even if they are the same flows, you can't make changes to the flows and see the results instantly (cos you're editing the cloud instance).




In fact, this could easily be extended to include any Inject nodes in the flows; the sidebar could present a list of all inject nodes and allow them to be 'triggered' remotely.

I think the implementation would be similar to the logger design described above - primarily going via the MQTT broker as command/response messages.
