### ISSUE TITLE
DB Mapping of Instances to Projects

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1720]
**Epic:** #1689 

In order for us to have multiple instances per project, we'll need to map these in the database.

Currently, there is no differentiation between a "Project" and the Node-RED instance bound to it, they are considered a single entity. It is likely that this piece of work will not be trivial.

As a first stage, we may wish to utilise the existing server-side and DB language/reference to "Project" and keep it that way. Alternatively, we could introduce the new concept of "Application" as proposed by @ZJvandeWeg - this will in turn make the migration easier given that we then change `Project` -> `Application` & `Instance`, rather than `Project` & `Instance`

**Comment by knolleary** [comment]
I'm getting a bit muddled with so many interconnected issues with some being meta discussions, some being front-end specific tasks and some being more general tasks.

I *think* this issue is specifically covering the renaming of Projects to Instances within the internals of the runtime - covering Database models and internal apis etc.

Following our discussions today around the required backend changes, we have agreed to start with #1735 - introduction the Application object that sits above Project/Instance.

Once we have done that, we will evaluate the work needed to migrate all of the existing Project terminology, apis and models to 'Instance'. Those are mostly internal changes and not necessarily critical path to supporting multiple instances per application.

**Comment by joepavitt** [comment]
For me, this was constrained to just being able to map an instance > application in the DB, such that I can get an API call to return the list of instances in a given application, which to start with would still be the 1:1 relationship

**Comment by knolleary** [comment]
For 1.5 all of the work is done in the frontend, calling existing APIs.

This specific task now falls under #1735 and doesn't need tracking separately, so I'm going to close this issue.
