### ISSUE TITLE
Error message on deletion of device

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge#1722]
### Current Behavior

When I delete a device I get an error message as follows.

Failed to delete device: AxiosError: Request failed with status code 404

The device does seem to delete correctly though.

Video of the issue - https://d.pr/v/yKuqRK

### Expected Behavior

I should not get an error message.

### Steps To Reproduce

Delete a device on FlowForge.

### Environment

- FlowForge version: 1.4
- Node.js version: FF Cloud
- npm version: FF Cloud
- Platform/OS: MacOS
- Browser: Current Chrome

**Comment by robmarcer** [comment]
I just noticed, sometimes the error code is 400 rather than 404.

**Comment by robmarcer** [comment]
The 404 error seems to happen when I delete a device which has actually already been deleted but is still showing in the UI.

**Comment by hardillb** [comment]
On digging this turned out to be a configuration option on the billing backend.

When updating the number of devices it updates the billing per device count, the device price object had been marked as `metered` which doesn't allow quantity to be set. This was different to how Staging was configured.

I have updated the price object settings and we have now tested and this is resolved.
