### ISSUE TITLE
Feature: Introduce a way to create an application without an instance

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1986]
Right now, it's only possible to create an application with a first instance. 

Creating an application without a first instance would make managing applications easier long term.

**Comment by joepavitt** [comment]
**Default State:**

<img width="1510" alt="Screenshot 2023-07-12 at 11 20 01" src="https://github.com/flowforge/flowforge/assets/99246719/e008d1d8-2d69-439a-a794-ef4dca8dced8">

**Option to _not_ create an Instance**

<img width="1505" alt="Screenshot 2023-07-12 at 11 20 11" src="https://github.com/flowforge/flowforge/assets/99246719/85e4c434-49fc-40c9-9606-dd17f30bf8e8">

**Comment by joepavitt** [comment]
Prototype: https://www.figma.com/proto/rMB2w5ZZUtTC0nxbwLYKJY/FlowForge-Platform?page-id=0%3A1&type=design&node-id=671-624&viewport=-217%2C-7784%2C0.82&scaling=min-zoom&starting-point-node-id=671%3A624&show-proto-sidebar=1&mode=design&t=KJCFXfQJ14BJt3f9-1

**Comment by Steve-Mcl** [comment]
Joe, I feel "unticked" is much nicer & much cleaner.

Due to there being _much less noise on the page_ it is much easier to "see"  the checkbox 

---

Alternatively:

Perhaps leave the box ticked but instead of having such a large form to deal with, the user is passed to the create instance after the application is created?  This then reduces duplication and gives us a chance to intercept a creation error and keep the user on the Create Application page until corrections are applied?

**Comment by joepavitt** [comment]
> Joe, I feel "unticked" (by default) is much nicer & much cleaner.

May be the case, but expect in 80-90% of the cases, we are expecting a user to want to create an Application _and_ an Instance, so the default behaviour should align with what is most common?

I've just updated the default slightly by indenting the Instance options, to hint that they're influenced by the checkbox a little more.

We also have, for the onboarding process, the idea of auto-creating all of this: https://github.com/flowforge/flowforge/issues/2475

**Comment by MarianRaphael** [comment]
Follow-up work after https://github.com/flowforge/flowforge/issues/2619

**Comment by Pezmc** [comment]
@joepavitt Are the mockups/prototype above up to date? i.e. the toggle box

**Comment by joepavitt** [comment]
Yep, as above please. Default state in _checked_
