### ISSUE TITLE
Cannot upgrade modules from inside Manage Palette

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2005]
### Current Behavior

Tried to upgrade our posthog node-red module from `1.0.1` to `1.1.0`:

<img width="761" alt="Screenshot 2023-04-14 at 07 44 00" src="https://user-images.githubusercontent.com/99246719/231966287-a044e0b8-994c-4878-8dd6-7613be407ae8.png">

Even after a restart, the version number did not change. I did manage to get it working by explicitly changing the version number in the Instance > Settings > Palette.

Even since then though, I still see the `module_not_allowed` errors, I see this twice because I attempted this twice. After the first attempt, this error only showed once.

### Expected Behavior

The modules should upgrade to the requested version upon restart.

### Steps To Reproduce

- Install a community module via "Manage Palette" in Node-RED
- Try to "upgrade" that module via the "Manage Palette" in Node-RED (you'll be told to restart)
- Restart the instance
- Check the version of the module inside "Manage Palette" - it has not changed and still offers the upgrade

### Environment

- FlowForge version: 1.6.0
- Node.js version: production
- npm version: production
- Platform/OS: Mac
- Browser: Chrome

**Comment by knolleary** [comment]
This is due to the way we track the installed modules independently of how Node-RED tracks it internally - and the fact Node-RED behaves slightly differently in the case of an upgrade request (rather than an install/delete request)

When a new module is installed/removed from the Manage Palette view, Node-RED updates its saved settings to record the node being added/removed. That results in a call back to the storage API we host in the forge app. We intercept the call, pull out the list of modules and sync it with the list we keep against the Instance (which is how we allow the user to edit the module list via the Instance settings view).

The problem with upgrade is that Node-RED isn't updating its list of installed modules; historically, Node-RED hasn't needed to care about the version so much, it just cared about the modules being added/removed. Because it doesn't update the list with the new version, the platform doesn't get the call to update its record of the modules and their versions.

However, there is a workaround. Doing an install or upgrade triggers a `nodes.install` audit event - that includes the module and version number. We can use *that* event to update our local record.

**Comment by knolleary** [comment]
The `{"code":"module_not_allowed"}` error isn't immediately related - not entirely clear on the circumstances for that.

> Even since then though, I still see the module_not_allowed errors, I see this twice because I attempted this twice. After the first attempt, this error only showed once.

Attempted what exactly? I don't see that in my local testing with other modules and not sure why you'd see it twice.

**Comment by Steve-Mcl** [comment]
Fixed in #2011 

Please perform manual checks on staging as outlined in the *Acceptance Criteria* in PR
