### ISSUE TITLE
Empty State: No Instances (/team//instances)

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2066]
Instance: One Node-RED w/settings, audit log, etc. etc.

**Comment by Yndira-FlowForge** [comment]
Here, there's only one NR instance to be created at the same time as the application.
(I'll work on [this](https://github.com/flowforge/flowforge/issues/2065#issuecomment-1531264284) here as well, did tried it but looks like it's too much, I need to try some ideas)
 
![03Empty State_ Team - Instances](https://user-images.githubusercontent.com/129537638/235659887-ba277577-9fe3-4dcf-a618-0fa5c2b1b1d4.png)

**Comment by Yndira-FlowForge** [comment]
I saw your red version, I like these, but maybe they become a bit more modern than what we're aiming? And the pastels add that cozy feeling...

I tried with the full red, doesn't look bad...

![Image](https://user-images.githubusercontent.com/129537638/235675836-8373c8c0-80be-4577-a210-92b2b0cae8ae.png)

But when I try to apply it to the next one... I feels like too much... 

![Image](https://user-images.githubusercontent.com/129537638/235677554-65051ec6-25a4-4ef3-b988-25a6eb9a7d13.png)


Originally, I only used the dark blue/gray palette because it's still more serious/industrial even though we're using the light variants...

I can try to add some colors, but maybe finish up all of them in the first style, to make sure we deliver on time, and then iterate... What do you think @joepavitt ?

**Comment by joepavitt** [comment]
The red surrounding line is too much. Red should be used sparingly has the harsher tones often imply "error". Agree though, let's focus on content first - styling/shading later.
