### ISSUE TITLE
Cannot select "Member" option when inviting a team member

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#2084]
### Current Behavior

Cannot select "Member" option when inviting a team member

https://user-images.githubusercontent.com/44235289/236152158-6e358a9a-43bc-4999-af8f-d08ae9d6afc2.mp4

### Expected Behavior

Either pre-select "Member" or permit "Member" selection

### Steps To Reproduce

1. open the "Members" page
2. click "Invite Member"
3. try to select "Member" option before any other.

### Environment

- FlowForge version: 1.6
- Browser: Chrome latest

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
I think this is a ui-components bug.

The options is presented via `ff-radio-group`:
```
<ff-radio-group v-model="input.role" orientation="vertical" :options="roleOptions"></ff-radio-group>
```

The default value of `input.role` is `Roles.Member` - so the group thinks that option is already selected, which is why clicking on it does nothing and why selecting another option lets you then select it again.

For some reason, `ff-radio-group` isn't initialising correctly.

**Comment by knolleary** [comment]
In fact, you already raised this https://github.com/flowforge/forge-ui-components/issues/122

**Comment by Steve-Mcl** [comment]
:doh: 

I knew I'd seen it but couldnt find the issue (low and behold it is in the other repo!).

Perhaps we should could keep this issue open too as the problem has surfaced in a different location? - it can be closed when the underlying issue is resolved and a manual test has been carried out?
