### ISSUE TITLE
Devices in DevOps Pipelines

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2243]
### Epic

https://github.com/flowforge/flowforge/issues/1492

### Description

As a: FlowForge User,

I want to: add devices to my DevOps pipeline,

So that: when executing the DevOps pipeline, a snapshot can be generated and the project is pushed to all devices of an instance.

### Which customers would this be availble to

Licensed Edition (EE)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
There are two separate pieces of work needed to achieve this story.

1. Pipelines need to deal with snapshots, rather than the way they use the export/import APIs today
     - when a pipeline stage runs, it generates a new snapshot on the source instance. That snapshot is then copied into the target instance and the 'rollback' api is used to deploy that snapshot on the target.
2. When creating a pipeline stage, its configuration should include an option to 'set target snapshot' when it is triggered - this only makes sense to do once the pipeline operations on snapshots.

**Comment by Pezmc** [comment]
This was released to staging under https://github.com/flowforge/flowforge/pull/2399, which updated the pipeline model to use snapshots. Snapshots can them be optionally pushed out to devices by setting the  deployToDevices flag.

**Comment by MarianRaphael** [comment]
https://github.com/flowforge/flowforge/pull/2399

**Comment by MarianRaphael** [comment]
Verified on staging with Mac as device
