### ISSUE TITLE
Instance settings: Add https.key and https.certs

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#2257]
### Description

As the `settings.js` is controlled by FlowForge, additional configuration might be needed to get the most out of devices.

In this case the devices require custom certificate settings, the devices than might need additional configuration. In this case we should introduce: `https.key` and `https.cert`.

## Customer requesting
1. https://app-eu1.hubspot.com/contacts/26586079/record/0-2/6568939245

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by ZJvandeWeg** [comment]
@Steve-Mcl I cannot get an initial sizing that makes sense, do you have an idea here?

**Comment by hardillb** [comment]
Making it clear this is a Devices request, NOT a cloud instance.

**Comment by knolleary** [comment]
From my understanding of the customer's scenario, in their existing (non-FF) NR instances this is something they already configure.

 I think it would be sufficient for us enable configuration of Https via the local config file of the device agent. This doesn't need to be centrally managed via instance settings at all for an MVP.

If we assume they are able to make the certs available to the device agent, the agent just needs to be told to use them.

Yes we need to consider cert expiry - we can discuss with the customer on how they manage that today as it may not be something for use to worry about initially.

**Comment by griemenschneider** [comment]
Thanks for considering this issue - I can add some customer perspective here. We wrap and deploy the agent in Docker; the cert is already packaged in that container so it is accessible to the agent. We've never experienced an expiration as we've managed so far to keep our certs always up to date. If the cert were to expire I would expect Node-Red to not start but the agent to survive and continue status updates to the platform. In this situation we are indifferent to falling back to HTTP because the upstream and downstream connections expect HTTPS anyways - so the instance might as well be down. An error message or error code indicating why Node-RED did not start would be helpful
