### ISSUE TITLE
Expand Trial Phase Features

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2282]
### Description

Currently, during the trial phase, users are only permitted to create one instance. However, the majority of FlowForge's features are based on the concept of multiple instances per application.

To enhance the onboarding experience for users, I suggest including all starter package features.

As a new user in the trial phase,
I want to be able to create two small instances and two devices,
So that I can fully explore and understand the various features of FlowForge

(While reducing the trial duration to 14 Days would be fine)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
I like this idea Marian. It allows the user to see the power of FF.

Additionally, I think having a default project (_starter flows_) that demonstrate the amazing features would go a good way to showing how simple FF makes things like interproject communication, a ready/live on-line secured dashboard (no effort - all by default) etc.

**Comment by ZJvandeWeg** [comment]
@MarianRaphael I think you're looking for leveraging the Stripe Trial features: https://stripe.com/docs/billing/subscriptions/trials#create-free-trials-without-payment

**Comment by knolleary** [comment]
We already have the trial logic built in and the plan is to continue using that - albeit lifting its existing restrictions to give full access to the new Starter TeamTier. There hasn't been any discussion on moving to Stripe Trials; we looked at them previously and they didn't fit our needs at the time.

Currently the Trial mode is enabled by Admin ticking the box in settings and identifying an InstanceType that a user is allowed to create whilst in Trial mode.

To meet the goals of this issue, that configuration will change so Admin will pick which TeamTier is treated as the Trial tier. When a user signs up and we auto-create their team and put it in trial mode. Whilst in trial mode, they aren't asked to setup billing, but are otherwise not restricted in what they can do within the limits of the team tier.

If a user opts to 'upgrade' their team whilst in the trial, I propose they leave the trial at that point in time - rather than trying to carry the trial over into a new team tier.
