### ISSUE TITLE
Updating any part of Docs seems to update the updated date on all pages

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge#2592]
### Current Behavior

The update date text on all the Docs pages seems to update if anything is changed on any page of Docs.

### Expected Behavior

Only updated pages should get an updated date.

### Steps To Reproduce

View any page of the Docs e.g. https://flowforge.com/docs/admin/#getting-started

https://d.pr/i/tRAFlx

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by knolleary** [comment]
The script that copies the files from the flowforge repo to the website repo when building the site injects the git modified date of each file into the yaml header.

https://github.com/flowforge/website/blob/f8b5646b98ff6e27abfdac72e4edf32bd9c4aaeb/scripts/copy_docs.js#L24C7-L29

This was done so that the website could display the proper modified date for the file when it doesn't have the git history (because the ff docs files aren't maintained in this repo).

It looks like this commit changed the page template not to use that value: https://github.com/flowforge/website/commit/9afdf54f138fe44233afac00607cf089cffc0b41#diff-588e5c43ca5d5bdf8c160c0adf415bb28c3fe3249a982ecf1a4a526153c0056a
