### ISSUE TITLE
More useful DevOps pipeline snapshot names

### ISSUE THREAD

**Issue by griemenschneider** [flowforge/flowforge#2600]
### Description

As a FF user I use the DevOps pipeline feature. During movement between pipeline steps a new snapshot is auto-generated. The snapshot has an auto-generated name and description, both of which could be more useful.

On our development team, typically snapshot names are the version numbers and the description of the snapshot is the changelog. In auto-generated snapshots it would be ideal if either the name or the description referenced the target snapshot they were created from.

Compare these two snapshots:
![snapshotExample](https://github.com/flowforge/flowforge/assets/135891848/dbc64a2a-4ffb-48a3-8f0b-082c14fb2458)

The snapshot marked #1 is auto-generated. The snapshot marked #2 was generated by our team.

For example, the auto generated snapshot could instead take the form [originalName]-Deployed Snapshot-[dateDeployed], such as: 5.1.1 - Deploy Snapshot - 2023-08-15 16:12:41

The description of an auto-generated snapshot could also include the original description.

### Have you provided an initial effort estimate for this issue?

I am not a FlowForge team member

**Comment by knolleary** [comment]
Hi @griemenschneider 

With the current iteration of the pipelines, when the pipeline runs it first generates a snapshot on the source instance and then copies it over to the target instance. Because it is generating the snapshot based on what is currently deployed at that point in time, there is no relationship to existing snapshots on that instance.

Reading between the lines of your description, it sounds like you would want an option on the pipeline to grab the most recent snapshot, rather than generate a new one?

**Comment by griemenschneider** [comment]
Thanks @knolleary - your response has taught me a little more about instances and the platform. As you've inferred my question was rooted in a misunderstanding of the DevOps pipeline.

Our team doesn't use instances very often; instead our workflow is:
1. create a snapshot from a device
2. roll the snapshot back
3. push the snapshot down the DevOps pipeline

I see now how Step #2 disassociates the snapshot created in Step #1. As you've implied, from our perspective the ideal case would be to push the snapshot from Step #1 directly in to Step #3. Or as an intermediate solution, allow us to add a description or name to the snapshot created in Step #2.

**Comment by Pezmc** [comment]
Hi @griemenschneider 

I've addressed this proposal as part of https://github.com/flowforge/flowforge/pull/2818, the naming of created snapshots is much more intelligent (it will persist any custom name you give), and it's possible to choose which snapshot you'd like to push, rather than a new one always being created. 

Please give it a look and let us know if you have any further feedback!

**Comment by griemenschneider** [comment]
Hey @Pezmc this looks great, thank you! Looking forward to using this new feature
