### ISSUE TITLE
FlowFuse Cloud sign-up did not send a welcome email

### ISSUE THREAD

**Issue by iskerrett** [flowforge/flowforge#2687]
### Current Behavior

After the 1.11 release, I signed up for FlowFuse Cloud. I received an email for verify my email but I did not receive a welcome email. I checked my spam folder and it was not there.

### Environment

- FlowForge version: 1.11
- Node.js version:
- npm version:
- Platform/OS: Windows
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Can confirm and recreated locally. Will have a fix to deploy in the morning.

**Comment by MarianRaphael** [comment]
Verified also on staging, 

I think it is due to
`this.trialInstanceTypes.unshift({
                    value: '_',
                    label: 'All team features'
                })`
in: frontend/src/pages/admin/TeamTypes/dialogs/TeamTypeEditDialog.vue

if "All team features" is selected in the frontend, trial.instanceType will be deleted, effectively setting it to null when the data is sent to the backend. As a result, the condition if (teamTrialInstanceTypeId) in setupTrialTeamSubscription would evaluate to false, and the email would not be sent.
