### ISSUE TITLE
View hashids

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#323]
### Epic

#224

### Description

**As a:** admin

**I want to:** be able to see the hashids for teams and projects on the admin view

**So that:** I can cross reference with the billing system

### Acceptance Criteria

- [ ] hashids are visible to admin

**Comment by knolleary** [comment]
For clarity - the hashid is exposed in the admin api as just the `id`. We shouldn't use the term `hashid` anywhere in the externals.

**Comment by joepavitt** [comment]
Is there actually a way in the Admin view to see the full list of Projects?

**Comment by knolleary** [comment]
No, we don't have that view today.

**Comment by joepavitt** [comment]
Given the request in this task is to show ids of Projects, am I just ignoring that part of the request, or adding a Project view too?

**Comment by knolleary** [comment]
At the moment, getting a full list of projects is too expensive an operation because it probes each project to get its status. That is something I want to look at in 0.4 (issue to be raised) - and will be a precursor to providing an Admin view of all projects (Story to be raised).

So for this item, adding the id to the team table is a good first step.

**Comment by sammachin** [comment]
Yep teams are the main one for now as they don't have unique names and there is a single combined view, they're also the billable entity so the ID's are how we cross reference to stripe.
