### ISSUE TITLE
Pressing Enter in the Team Delete modal triggers cancel

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#334]
### Current Behaviour

Attempting to delete a team doesn't delete the team

### Expected Behaviour

Pressing enter after entering the team name (valid) should select "done" not "cancel" or just reload the page.

### Steps To Reproduce

- Create team
- Select Delete team from Team Settings page
- Type name of team in modal
- Press Enter
- Page reloads but doesn't delete the team

### Environment

- FlowForge version: 0.2.0
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: Linux
- Browser: Chrome

**Comment by sammachin** [comment]
Same applies to the delete project modal.

**Comment by sammachin** [comment]
Can re-create

**Comment by joepavitt** [comment]
Yeah, this is an issue across all of our dialogs in FlowForge. Consequence of how we handle `<template>` and because we expect a user to pass through a `<form>`. By default, `<form>` then expects an `@submit=""`. When this is not defined, it just refreshes the page (current behaviour in 0.7.0, noting this was raised back in 0.2.0).

We have plans to reduce the number of identical dialogs across our application by registering them through JS, instead of HTML (see https://github.com/flowforge/forge-ui-components/issues/26). In doing so, that should prevent this issue occurring, however, the timeframe on that (whilst planned for 0.8) may be a little while as it's a larger piece of work.

As a result, I will ensure the `@submit=""` is defined in all existing `<ff-dialog>` instances within FlowForge to resolve this issue.
