### ISSUE TITLE
Admin Can't delete an invited user

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#339]
### Current Behavior

As as admin if I view the list of users invited to the platform at `/admin/users/invitations` There is a delete icon next to the user, however this does not appear to do anything.

If I go into the team that the user was invited to eg `/team/myteam/members/invitations` and delete from there it does remove the user

### Expected Behavior

The delete button in admin should be functional

### Steps To Reproduce

Invite an email address to a team
Goto `/admin/users/invitations` and click the delete button

### Environment

- FlowForge version: 0.2.0
- Node.js version: 16.x
- npm version: 8/x
- Platform/OS: Debian
- Browser: Chrome v99

**Comment by knolleary** [comment]
The event handler for the delete icon is there... just with commented out code. Need to see why it was commented out - could be a placeholder copied over from the team invitation page, or there could be a missing bit of api under the covers. Either way, the fix is to implement this function properly:

https://github.com/flowforge/flowforge/blob/main/frontend%2Fsrc%2Fpages%2Fadmin%2FUsers%2FInvitations.vue#L54

**Comment by joepavitt** [comment]
@knolleary @hardillb seems as though we have no end point to remove an invitation. nothing in [Forge API docs](https://docs.google.com/spreadsheets/d/1hEqul03TdALwsAawCMNMd9Fn7XlNVIFtFrCXF3Yekic/edit#gid=0), nor the source [code](https://github.com/flowforge/flowforge/blob/main/forge/routes/api/admin.js) that I can see.

**Comment by joepavitt** [comment]
> 

Ignore that - realised that the invitation endpoints for inviting/deleting aren't at the `/admin` endpoint where the `GET` for `/invitations` is, but at the `/teams` endpoints instead
