### ISSUE TITLE
Delete project confirmation dialog has broken layout

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#424]
### Current Behavior

In the delete project confirmation dialog, the styling of the project name overlaps the surrounding text:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/51083/160612704-1f7021dd-0f9d-4fdd-8b8b-9724a84cacfb.png">

### Expected Behavior

The text should not overlap itself

### Steps To Reproduce

1. create a project
2. Go to project settings -> Danger section -> Click Delete Project

### Environment

- FlowForge version: 0.3

**Comment by knolleary** [comment]
@fakoredeDamilola you are certainly welcome to. I would suggest the simple fix is to ensure the project name is on a newline of its own, rather than trying to have it inline with the rest of the text.

**Comment by knolleary** [comment]
Found another instance of this on the Create Team page.

<img width="198" alt="image" src="https://user-images.githubusercontent.com/51083/161251669-5990349d-f48b-48bb-bfbc-de4d49f727c0.png">

**Comment by fakoredeDamilola** [comment]
Hello can you help me
1) I signup the last time, but I dont think I can remember my password, I cannot find a signup page or a flow for forget password etc
![image](https://user-images.githubusercontent.com/47531232/161485102-c861362d-9cdf-4000-8d8c-a60c38586179.png)
2) @joepavitt I tried what you said for the long term, just for this error, and doing this
`'<pre><code block="inline">{{team.name}}</code></pre>'`
actually removes that code sort of default styling, the background and all and I dont think you will want that
A solution I came up with was to make it a block text based on the length of the string i.e greater than 14

**Comment by knolleary** [comment]
1. We don't have a password reset workflow in place today. If you've forgotten the administrator password, the only way back in is to edit the database directly - not easy to do as you need to generate a proper password hash.

> A solution I came up with was to make it a block text based on the length of the string i.e greater than 14

This doesn't need any logic. The dialog should place the project name on a line of its own - that is all.

**Comment by joepavitt** [comment]
Thanks @fakoredeDamilola - worth noting the long term solution with the `<pre><code block="inline">{{team.name}}</code></pre>` will require quite a lot of other work too, in particular with css changes. We have bigger plans for this, so sticking with the short term solution as Nick as suggested is the way to go at the moment. Thanks for helping out on this.

**Comment by fakoredeDamilola** [comment]
Hello @joepavitt @knolleary 
I made a PR https://github.com/flowforge/flowforge/pull/444

but please can you help me find a solution to the login issue I mentioned above, I tried new emails to see if I could open a new account but nothing worked
This is a lovely project and I would love to test, use, find some likely errors and pick up more tasks and work on them but I will need to have access.
thank you

**Comment by hardillb** [comment]
The quickest way to reset the admin password is to stop the app and delete the database file `var/forge.sql`. **WARNING** This will reset the whole application to it's first run state so make sure you have stopped and deleted any running projects before you do this.

You will then need to go through the setup wizard again when you start the application again.

The other option is to enable email support and this will allow you to reset the password. There is a debug/testing setup that will just print the emails to the logs rather than send them that will probably help

Add the following to the `etc/flowforge.yml` (or create a `etc/flowforge.local.yml` by copying the existing `etc/flowforge.yaml` and add it to the end)

```
email:
  enabled: true
  debug: true
```

**Comment by joepavitt** [comment]
Just found this issue is also present in the "delete project" dialog:

<img width="387" alt="Screenshot 2022-04-06 at 12 09 25" src="https://user-images.githubusercontent.com/99246719/161961940-5926d6e2-afd6-4d15-8987-8ba6aaeb5b55.png">

In addition to the instance found by Nick on the Create Team page.

@fakoredeDamilola can you take a look at these two as well please and then update the PR?

**Comment by knolleary** [comment]
@joepavitt just to note, the original issue is for the delete project dialog :)

So the two views that need fixes are:

 - Delete Project
 - Create Team

**Comment by joepavitt** [comment]
In that case, the [fix](https://github.com/flowforge/flowforge/pull/444/files) that @fakoredeDamilola has put in also fixes a third that was in the "Delete Team" dialog.
