### ISSUE TITLE
User can push a project to a device

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#460]
### Epic

#446 #447

### Description

**As a:** user

**I want to:** be able to push my project to an assigned device

**So that:** it will run on the edge device

### Acceptance Criteria

- [ ] User can select a device from within the project
- [ ] Project is pushed to the Edge Agent on the device
- [ ] Project runs locally on the device
- [ ] Device record in database is updated with time of last push
- [ ] Event in Audit Log
- ...

**Comment by knolleary** [comment]
I'm putting a large sizing on this as it touches a lot of parts of the system and there are lots of steps to consider and lots of technical questions to answer that we cannot easily answer until we're underway building it.

 - frontend design needed for how a user triggers the push - can be fairly simple for MVP
 - runtime needs to package up the project - similar to #268 and related stories - which becomes a snapshot of the project at that time. But the problem is then where that snapshot is stored....
 - runtime has to store that snapshot so it can be sent to/retrieved by the devices - that would be easier if we had the concept of Project Versions already (sort of related #218) so the device is told the project+version combination. But we don't have that. So we need to add something that doesn't then make doing Project Versions properly later any harder.
 - Edge Agent then needs to know how to retrieve and unpack that project snapshot and then run it.

**Comment by knolleary** [comment]
With the work done in #547 we have code that can generate a single JSON blob of a project state - including flows.

That is the starting point for what we'll push to devices.

As I describe in my previous comment, there are still quite a few parts to figure out here.

### Deployment policy

AKA - when does the platform push updates to devices.

1. **Fully Automatic** - *any* change to a project configuration, including flows is pushed to the devices. This is the most seamless for the user, but will potentially cause a lot of churn on the device.
3. **User triggered** - I think this is better for the user experience we'll have in 0.6. A user develops their flows in the cloud instance - hitting deploy repeatedly as they get it working. Once happy, they want to trigger a push out to the project devices.

### Project Snapshot

This has big overlaps with #587 - the question is how much do we want to overlap and avoid duplicate work.

I think we need to introduce the concept of a `ProjectSnapshot` as that is what gets pushed to devices.

**Comment by sammachin** [comment]
A good iteration on the Deployment policy would be to start with User Triggered and then we can later add a check box for fully auto, so you can have it on manual during active dev then switch on/off auto as required later.

**Comment by ZJvandeWeg** [comment]
@knolleary I've seen the demo of this, as such I anticipate this issue should be closed?

**Comment by knolleary** [comment]
Through #448 and the work done in the Agent repo, this functionality is done.
