### ISSUE TITLE
MQTT Broker within FlowForge

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#464]
### Description

To improve the efficiency of how launchers/devices report status and receive commands, we want to introduce an MQTT Broker into the FlowForge architecture. It will also enable a custom set of nodes described in #662 to provide seamless cross-project communication.

This story does **not** cover external usage of the broker. See https://github.com/flowforge/flowforge/issues/738 for the story covering that

---

 - [x] https://github.com/flowforge/flowforge/pull/706
 - [x] https://github.com/flowforge/flowforge-device-agent/pull/22
 - [x] https://github.com/flowforge/flowforge/issues/662

**Comment by sammachin** [comment]
Some simple options could be, the Aedes node within Node-RED provides a broker inside NR
However this is not workable in FlowForge today because external TCP connections are not permitted.
Solving the TCP connection issue may be an alternative here.

**Comment by hardillb** [comment]
> Solving the TCP connection issue may be an alternative here.

I believe this basically means giving each project their own IP address which I don't think i feasible (Given cost of buying IPv4 address ranges these days).

**Comment by sammachin** [comment]
doesn't have to be a whole IP address, each project could just be given a single random port.

**Comment by sammachin** [comment]
or possibly using SNI if connections were all TLS

**Comment by hardillb** [comment]
The comment was in regard to the the generic TCP access problem, not specifically MQTT.

We will need to look at the options for none HTTP load balancing (this is how K8s talks about this stuff) in AWS EKS

**Comment by PLCMercenary** [comment]
Host a broker cluster and give each project a mount point. we can surely make the subscribe connection to a broker from a project right?

**Comment by PLCMercenary** [comment]
If this issue is still being discussed, I think a simple solution would be to host a broker cluster, it doesnt matter where it is, as long as we can expand to additional compute resources. we ingress everything using a dns address, `mqtt.flowforge.cloud`
then just assign mount points for each admin username, or per the project. it would be simple to generate a user id on creation if the instance, and then provide a key, the mount point is then set in the backend table with a simple update and i believe the process update is a change hook for the table.

**Comment by ZJvandeWeg** [comment]
@knolleary Would appreciate your thoughts here. In general I tend to understand this as: https://github.com/flowforge/flowforge/issues/464#issuecomment-1095317433

We should ship 0.7 with a Bring your own broker, but a working version for FF.cloud.

**Comment by knolleary** [comment]
We need to be very careful to not think BYOB solves this properly.

For a FF Enterprise install, the customer can of course choose to run their own MQTT broker and use the standard MQTT nodes in NR to communicate with it. That is one valid definition of BYOB. However it does make the significant assumption that they implement their own security on the broker - controlling what credentials can publish/subscribe to what topics spaces.

When it comes to FF.cloud - we need to get the security model right from the start and it *must* be integrated with the Team/Project security model.

To implement the magic 'communicate between projects' nodes, we need to provide credentials for those nodes to connect to the appropriate broker. If this was running entirely inside FF.cloud (where the end user doesn't have access to the underlying credentials etc inside the container) then we could do the appropriate MQTT topic handling in the nodes to keep it secure.

The problem comes when you consider Devices - which we definitely do want to consider here. This is because the code is running outside of FF.cloud - so the credentials to connect to the broker are outside of our control. Those credentials **must** only allow the the client using them to use very specific MQTT topics. Otherwise it would be able to subscribe to *any* messages on the broker and snoop on what is being sent by anyone.

The point I'm getting to is we need much more than 'just run our own mqtt broker in ff.cloud'. We need to integrate it in such a way to be able to provision new credentials on the broker for each project and device, with suitable topic access control in place to restrict what it can do. That type of integration is going to be specific for the flavour of MQTT broker we use - and is critical to get right.

On the basis that we definitely want to go in this direction, the next steps are:

 - design the topic namespace used by projects to enable cross-project communication without allowing any unintended access to other topics
 - identify what broker we want to run in ff.cloud. This has to be evaluated based on:
    - ability to dynamically provision users/topic restrictions
    - able to scale (or at least, have some idea as to how we would scale in the future)

**Comment by knolleary** [comment]
Figma design doc (sharing ahead of a design working session, so currently no content to see...) - https://www.figma.com/file/BODuex2gt5E3d1KG4sXgAn/MQTT-Broker?node-id=0%3A1

**Comment by knolleary** [comment]
On the working assumption we'll use mosquitto as the broker of choice initially, we need to map the above table of topics to mosquitto users/roles/groups.

### Roles

- `forge_platform` is the role assigned to the client the forge platform connects with.

Role |  ACL Type  | Topic Filter  |  Permission
-- | -- | -- | --
`forge_platform` | subscribe | `ff/v1/+/p/+/status` | allow
  | subscribe | `ff/v1/+/d/+/status` | allow
  | publishClientSend | `ff/v1/+/p/+/command` | allow
  | publishClientSend | `ff/v1/+/d/+/command` | allow


 - `team-<tid>` is created for each team

Role |  ACL Type  | Topic Filter  |  Permission
-- | -- | -- | --
`team-<tid>` | subscribe | `ff/v1/<team>/p/+/out/+/#` | allow
  | publishClientSend | `ff/v1/<team>/p/+/in/+/#` | allow

 - `launcher-<pid>-admin` and `project-<pid>` created for each project

Role |  ACL Type  | Topic Filter  |  Permission
-- | -- | -- | --
`launcher-<pid>-admin` | subscribe | `ff/v1/<team>/p/<project>/command` | allow
  | publishClientSend | `ff/v1/<team>/p/<project>/status` | allow
  |   |   |  
`project-<pid>` | subscribe | `ff/v1/<team>/p/<project>/in/+/#` | allow
  | publishClientSend | `ff/v1/<team>/p/<project>/out/+/#` | allow

 - `device-<did>-admin` created for each device in the team

Role |  ACL Type  | Topic Filter  |  Permission
-- | -- | -- | --
`device-<did>-admin` | subscribe | `ff/v1/<team>/d/<device>/command` | allow
  | publishClientSend | `ff/v1/<team>/d/<device>/status` | allow
  |   |   |  



### Groups

For each project/device the following groups are created:

Group ID | Roles assigned to group
-- | --
`project-<id>` | `team-<tid>`, `launcher-<pid>-admin`, `project-<pid>`
`device-<id>` | `team-<tid>`, `device-<did>-admin`, `project-<pid>`

**Comment by knolleary** [comment]
A consequence of 2 is the need to introduce team tiers *before* we do this work. We can still do the technical work (and there is a lot of it to be done - possibly more than we can contain in one release) to add an MQTT broker to the environment for 0.7, but we won't have any new features to talk about for end-users.

**Comment by sammachin** [comment]
Yes 2 also depends on the custom nodes, https://github.com/flowforge/flowforge/issues/662  so there may be something to consider there, or we may want to delay that work

**Comment by hardillb** [comment]
**MQTT broker URLS.** 

Been thinking and playing. Current thinking is that we should have 2, internal and external. Internal will be used by projects, External will be used by Devices. For all all the Container drivers it makes sense to keep the comms inside the system (both speed and cost).

**Internal**
 - LocalFS will always be localhost (we just say the broker must be co-located with the projects/forge runtime
 - Docker uses the broker container name and just works
 - K8s uses broker service name and just works

No need for TLS/SSL (yet) as all running on loopback or inside the Container Orchestration system

**External**
 - LocalFS will use the external IP/hostname of the install
 - Docker/K8s will use MQTT over WS and will use mqtt.<domain> and will use the same Ingress reverse proxy as the projects. 

This automatically handles WSS and means we don't need to work out how to expose arbitrary TCP services

**Comment by Steve-Mcl** [comment]
All - first up, apologies if the below proposal is a tough read, there are many concepts still floating around and I can not keep iterating in my head - so will post what I have as a basis to grow from. 

I will continue to review and refine in the coming days but would greatly appreciate thoughts and direction.

# Project links design notes

## Concepts
The high level concept of project links is **inbox**/**outbox**  
**inbox** being what is sent directly to a project (a project/device has its own inbox)  
**outbox** being what a project broadcasts to anyone who cares to listen  

Other notes...
* Some nodes will need a project selector that it gets from API
* To support a tree like "picker" (as per link-in/out) nodes, it would be necessary to populate $hidden topics for discoverability
  * This is potentially negated if we permit free form `sub-topic` design
* Node will likely need settings entry in settings.js (to point to API atc)
  * If not found, project-link nodes should not be added to palette & raise error in console
* Instance will likely need Env Vars (device ID etc)


## Topic structures

### Details (From the proposed Subscription ACLs)
Subscription ACLs | Can subscribe to... | Publish ACLs | Can publish to...
-|-|-|-
Receive messages from other projects | `ff/v1/<team>/p/<own-project>/in/+/#` | Send messages to other projects | `ff/v1/<team>/p/<any-project>/in/+/#`
Receive broadcasts from other projects | `ff/v1/<team>/p/<any-project>/out/+/#` | Send broadcast message | `ff/v1/<team>/p/<own-project>/out/+/#`

### project to project
* `ff/v1/<team>/p/<any-project>/in/<level1>/<leveln>`
  * `<any-project>` is the target you want to send to
  * `<level1>` is equivalent to `motor1` in the example `motor/1/speed`
  * `<leveln>` is equivalent to `1` and `speed` in the example `motor/1/speed`
  * There must be at least a `level1` topic, sub topics are optional
* Free form MQTT style topic e.g. `power/status`, `waterflow/status`, `monitor/motor/1/speed`, etc
* **NOTE**: the user facing topic must NOT start with a `/` as is appended to the underlying topic structure
* **Thought**: may be desirable to identify the source-project. This could be in the topic or in the v5 `userproperties`?
  * use-case: **project-DEVICE1** wants to identify which project-instance updated a certain topic!
  * use-case: **project-main** receives an event from **project-v2** and routes/processes it differently to events from **project-v1**

### broadcast
* `ff/v1/<team>/p/<own-project>/out/<level1>/<leveln>`
  * `<own-project>` is the ID of this project
  * `<level1>` is equivalent to `motor1` in the example `motor/1/speed`
  * `<leveln>` is equivalent to `speed` in the example `motor/1/speed`
  * There must be at least a `level1` topic, sub topics are optional
* Free form MQTT style topic e.g. `power/status`, `command/stop`, etc
* **NOTE**: the user facing topic must NOT start with a `/` as is appended to the underlying topic structure




## Scenario "Wind Farm" 
Regarding the initial design work for "Project Link" plugin, it is helpful to me (and hopefully others) to have a human digestible scenario based on the table of topics (https://github.com/flowforge/flowforge/issues/464#issuecomment-1155300019)

### Team
A small team of 6 people manage a small wind farm (20 devices). 
* 1 Admin - Environment setup / owner
* 2 IS/IT - maintain the a project for supervisory control and data acquisition
* 3 Engineers - maintain the device projects

The team name for this scenario is **"wind-farm-1"**

### Projects
* **project-main** - supervisory control and data acquisition 
* **project-v1** - a project for the 10 old v1 hardware devices
* **project-v2** - a project for the 10 newer v2 hardware devices

### Devices
* 10 devices use Project **project-v1** (old v1 hardware)
* 10 devices use Project **project-v2** (new v2 installations)

### **project-main**
* Will receive status info from all devices
* Provide a dashboard for realtime status
* Log various status and CBM data to DBs for long term trending and predictive maintenance
* Ability to command individual devices
* Ability to broadcast commands to all devices

### **project-v1**
* This is the flow files for v1 devices (old internal hardware)
* should emit machine status to **project-main** (current state) using agreed format V1
* should receive and action commands from **project-main** using agreed format V1

### **project-v2**
* This is the flow files for v2 devices (newer internal hardware)
* should emit machine status to **project-main** (current state, CBM data, internal device heartbeats etc) using agreed format V2
* should receive and action commands from **project-main** using agreed format V1


### Overview

```mermaid
  graph TD;
    classDef team fill:#555,stroke:#333,stroke-width:2px
    classDef project fill:#aaa,stroke:#333,stroke-width:2px,color:#000
    classDef device fill:#cef,stroke:#123,stroke-width:2px,color:#000

    PM[/project-main/]:::project---PD1[/project-v1/]:::project;
    PM----PD2[/project-v2/]:::project;

    PD1---PD2;
    PD1---Device_1:::device;
    PD1---Device_2:::device;
    PD1---Device_x:::device;
    PD2---Device_11:::device;
    PD2---Device_12:::device;
    PD2---Device_1x:::device;
```

<br>


## Project-Link Nodes: design proposal

### Base principles
* The design pattern will follow suit of the Node-RED `link-in/out/call` nodes.
  * The `project-link-in/out/call` nodes transmission should be considered an envelope and the data passed is a complete `msg` object
    * This can then include a topic/payload and any other properties required
  * To achieve command/response patterns, users can either...
    * use **project-link-in/out** nodes to respond 
    * use **project-link-call** to get end-to-end feedback
* The complete node, when pointed at a **project-link-out** node should be able to determine the envelope was successfully "sent"
* The complete node, when pointed at a **project-link-call** node should be able to determine the envelope was successfully "delivered and returned"??
* The **project-link-call** will require a `timeout` property similar to `link-call`


### **Project-Link-Out** (Project to Project)
#### UI (User Facing)
A node can send a `msg` on the "Send messages to other project" topic structure
e.g. 
* target: `project-main`
* sub-topic: `motor/1/speed` data: `{"uom":"rpm", "value":"400"}`
#### Backend
the user facing topic `motor/1/speed` would be `ff/v1/wind-farm-1/p/project-main/in/motor/1/speed` under the hood.

### **Project-Link-Out** (broadcast)
#### UI (User Facing)
A node can send a `msg` on the "Send broadcast" topic structure
e.g.
* target: `all`
* sub-topic: `motor/1/speed` 
#### Backend
The user facing topic `motor/1/speed` would be `ff/v1/wind-farm-1/p/<own-project>/out/motor/1/speed` under the hood.
Any project wishing to receive a broadcast would subscribe to `ff/v1/wind-farm-1/p/<any-project>/out/motor/1/speed`

### **Project-Link-Out** Design
Philosophy - Project-Link nodes will transmit a `msg` just like the `Link-in/out` nodes.
From the above, we can conclude the **Project-Link-Out** node requires the following fields...
* **Target**: `["all", ...list_of_projects_in_THIS_team]`
  * selecting `<project>` from the list would perform a project-to-project transmission
  * selecting `all` would perform a broadcast transmission
* **sub-topic**: a tree enumerated from all projects & topics defined by **Project-Link-In** nodes (open to debate: this may be a future iteration)

Additionally, to support the equivalent of the `link-call`, this node should support 2 modes.
* "send to connected links"
* "Return to link call"


### **Project-Link-In** (Project to Project)
#### UI (User Facing)
The "in" node will receive a `msg` that is sent from another project where the sub-topic matches "Send messages to other project" structure
Accessing data from `project-v1` in `project-main`, the user would select the source project e.g. `project-v1` and enters a topic e.g. `motor/1/speed`
#### Backend
* Accessing data from `project-v1` sub-topic `motor/1/speed` at project `project-main`...
  * The node subscribes to the user facing topic `motor/1/speed` as `ff/v1/wind-farm-1/p/project-v1/in/motor/1/speed` 

### **Project-Link-In** (broadcast)
#### UI (User Facing)
Accessing data from all projects in the team, the user would select the source project`all` and enter a sub-topic e.g. `motor/1/speed`
#### Backend
In accessing data from all projects in the team with sub-topic `motor/1/speed`, the **Project-Link-In** node subscribes to `ff/v1/wind-farm-1/p/+/out/motor/1/speed` 

#### *Project-Link-In** Design
From the above, we can conclude the **Project-Link-In** node requires the following fields...
* **Target**: `["all", ...list_of_projects_in_THIS_team]`
  * selecting `<project>` from the list would be to only receive transmissions from a single project
  * selecting `all` would receive transmissions from a all projects (broadcast)
* **sub-topic**: a tree enumerated from all projects & topics defined by **Project-Link-Out** nodes (open to debate: this may be a future iteration)



### **project-link-call** (for command/response pattern)
The **project-link-call** node functions like the current `link-call` node in that it expects a `project-link-out` node to return the msg along with the original `msg` sub properties identifying the caller
#### UI (User Facing)
* TODO
#### Backend
* TODO

#### Design
From the above, this proposal suggests the use of MQTT v5 response topic for routing back to the caller.
* **Target**: `[...list_of_projects_in_THIS_team]`
* **sub-topic**: typedInput [str, msg, env] (open to debate)

#### Notes
* Should support nested calls
* Should be restricted to single target?
* sub-topic must not contain wildcards?


### Additional thoughts / iteration...
* The UI field name `sub-topic` is open to debate but should try not to call it `topic` since it is actually a sub-topic or topic extension 
* Ability to list projects and **Project-link-in** nodes in that project for target selection
* Dynamic Link-call capability (in line with current Link-call nodes)
* If a data schema were permitted this could be advertised for simple tree-browse picking of values at the **Project-Link-In** node
* Consider means of discoverability of data sent (under the hood retained $topics) 
  * Using a hidden retained topic, we could provide "last msg" info in the `project-link-in` so the user can "copy path" without ever deploying (aids development)
* Show link target as clickable ghost node (in line with current link nodes)
  * May require modifications to node-red to provide deep linking capability
* Should MQTT v5 extended features by utelised to provide richer context
  * e.g. using `userproperties` we could include a specific ENV VARs (like device ID, event time)
   


---

**Comment by knolleary** [comment]
I've updated the topic table in  https://github.com/flowforge/flowforge/issues/464#issuecomment-1155300019 so that devices can subscribe to a common command topic for a given project - whilst allowing the launcher to have its own separate command/status topic space.

**Comment by hardillb** [comment]
Can this be closed now?
