### ISSUE TITLE
docker setup v0.4.0 hitting 503 error with Nginx (service temp. unavail.)

### ISSUE THREAD

**Issue by BasSwildens** [flowforge/flowforge#482]
When trying to setup flowforge on ubuntu20.04 with docker-ce I keep hitting a 503 error with nginx (service temp. unavail.). Changed `flowforge.yml` according to documentation:

```
port: 3000
host: 0.0.0.0
domain: t*******.nl
base_url: http://forge.t*******.nl:3000
api_url: http://forge:3000
```
Any idea where to look for this issue?

Regards, Bas

**Comment by hardillb** [comment]
You shouldn't need the port `3000` on the end of the `base_url`.

**Comment by hardillb** [comment]
If that doesn't work please include a lot more detail about the exact steps you followed when seeing the error and I'll look in the morning.

**Comment by hardillb** [comment]
@BasSwildens I've tested this morning with the following steps:

- clone docker-compose project
- run ./build-containers.sh
- edit `/etc/hosts` so `forge.example.com` points to docker-compose machine (same as setting up DNS wildcard to test)
- no changes to `etc/flowforge.yml` since using `example.com` as domain for test
- run `docker-compose up`
- point browser at `http://forge.example.com` and I get the setup wizard

As mentioned in the earlier comment the `base_url` should not have the `:3000` port number if using the nginx proxy setup in the docker-compose file.

```yaml
port: 3000
host: 0.0.0.0
domain: t*******.nl
base_url: http://forge.t*******.nl
api_url: http://forge:3000
```

Can you confirm if this is now working for you or supply the details I asked for last night.

**Comment by BasSwildens** [comment]
Hi, thanks for your fast reaction.

Followed same steps for setting up docker containers, except for changes to `etc/hosts` (instead added *.mydomain.nl to DNS domain settings pointing to docker-compose machine) and removed `:3000` from `base_url` but still having same 503 error. 

docker_compose logs --tail=20
![image](https://user-images.githubusercontent.com/38854481/163999709-c329390e-3851-400f-bcd5-b947de8015a6.png)

**Comment by hardillb** [comment]
Can you run `docker inspect docker-compose_forge_1` and check the `Env` section for the `VIRtUAL_HOST` entry

It should read `forge.mydomain.nl`

```json
            "StdinOnce": false,
            "Env": [
                "VIRTUAL_HOST=forge.example.com",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=16.14.0",
                "YARN_VERSION=1.22.17",
                "FLOWFORGE_HOME=/usr/src/forge"
            ],

```

**Comment by BasSwildens** [comment]
Getting a 'no such object'

![image](https://user-images.githubusercontent.com/38854481/164003623-42d27319-7f5a-4815-bc26-2732a00c5887.png)

**Comment by BasSwildens** [comment]
ah, typo

![image](https://user-images.githubusercontent.com/38854481/164004689-bcadbfa7-a6b1-49a3-b9a8-803a0677a0ff.png)

**Comment by hardillb** [comment]
OK, I can see what's wrong. The instructions need updating to point out that you need to edit the `docker-compose.yml` file as well to update the `VIRTUAL_HOST` entry to match your domain.

I'll raise a doc bud

**Comment by BasSwildens** [comment]
changed `docker-compose.yml` and getting setup page, thanks!
