### ISSUE TITLE
Create Project button non responsive 

### ISSUE THREAD

**Issue by PLCMercenary** [flowforge/flowforge#483]
### Current Behavior

Creating a project from the Projects tab. 

Clicking the "Create Project" does nothing 

### Expected Behavior

Clicking the create project button opens the create project dialog

### Steps To Reproduce

Start flowforge instance, create login, create team, create template, create stack. 

login as user 
If there are NOT any existing projects when user navigates to the projects, tab there is a visible "create project" button. 

If there are existing projects available in the projects tab this button is not visible

### Environment

- FlowForge version: 0.4
- Node.js version: 16
- npm version: 
- Platform/OS: Docker / Fedora Server 36
- Browser:  Safari / Brave

**Comment by sammachin** [comment]
There is a create project button on the overview tab `team/[TEAM]/overview`, this works.

On a team with no projects there is a create project button on the `team/[TEAM]/projects` page, this does not work in 0.4 (worked in 0.3)
![Screen Shot 2022-04-20 at 9 08 54 AM](https://user-images.githubusercontent.com/187645/164184789-ec42e9ce-432b-4289-9ae4-f9b38332ec1e.png)

The offending code looks to be around https://github.com/flowforge/flowforge/blob/main/frontend/src/pages/team/components/ProjectSummaryList.vue#L24

Compared to the working button at https://github.com/flowforge/flowforge/blob/main/frontend/src/pages/team/components/ProjectSummaryList.vue#L24


This button is also missing from the projects tab when there are existing projects, this should be fixed in the rebrand.
