### ISSUE TITLE
project to crash status when stopping/restarting

### ISSUE THREAD

**Issue by vdwpsmt** [flowforge/flowforge#530]
### Current Behavior

After a project crash and state  in **crash** state,
when trying to restart the project again, I get an error "address already in use"

`5/3/2022 2:03:19 PM
[error]
Uncaught Exception:
5/3/2022 2:03:19 PM
[error]
Error: listen EADDRINUSE: address already in use 0.0.0.0:7882
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at doListen (node:net:1516:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)`

### Expected Behavior

Clean start and stop

### Environment

- FlowForge version: 0.4.3
- Node.js version: 16.14.2
- npm version: 8.8.0
- Platform/OS: Windows_NT 10.0.19042 x64 LE
- Browser: edge
- Node-RED version: v2.2.2

**Comment by vdwpsmt** [comment]
Hi, 
Meanwhile I did some extra research.  The root cause is most likely not related to flowforge.
```
5/3/2022 4:22:53 PM[info]Stopped flows
5/3/2022 4:22:53 PM[]
3 May 16:22:53 - [red] Uncaught Exception:
5/3/2022 4:22:53 PM[error]Error: Already disposing    at OPCUACertificateManager.<anonymous>..... 
```
an OPC-UA node is badly configured which causes this NR instance to crash when I try to deploy.
the NR UI gives the pop-up message `Lost connection to server, reconnecting..`
As a consequence I go back to my flowforge UI and there I notice flowforge doesn't seem to be aware of this crash.  It still says the status of this NR project is running.   
![image](https://user-images.githubusercontent.com/41926598/166473146-d6641ba8-5fd5-4b15-a4d0-514fae81c27a.png)
As they seem out of sync, I try restarting the project (Actions -> restart) and I get this: 
![image](https://user-images.githubusercontent.com/41926598/166475028-0d9801e2-33f0-488c-85e4-db01c6d309d3.png)

**Comment by knolleary** [comment]
Hi @vdwpsmt , sorry for the slow response.

There are a few different bits to cover here.

> an OPC-UA node is badly configured which causes this NR instance to crash when I try to deploy.

The [wrapper](https://github.com/flowforge/flowforge-nr-launcher) we use to run Node-RED monitors for crashes and automatically restarts it. If it detects repeated crashes, then it stops Node-RED - you can see the log message at the bottom of the first screenshot `"restart loop detected..."`.

Now, I would have expected it to try to restart NR in Safe mode - so you would be able to access the editor without the flows running and modify whatever is needed to fix the issue. But it doesn't do that. I need to walk through it with @hardillb to make sure I'm not missing something about why we shouldn't do that here.

> As a consequence I go back to my flowforge UI and there I notice flowforge doesn't seem to be aware of this crash. It still says the status of this NR project is running.

This is a current limitation - the platform only refreshes the project status when you reload the page or trigger it to reload the project information such as navigating away from the project and back again. We have an item on the back to improve this, starting with #370.

---

The crash you are getting *after* the original error from the OPCUA node (`EADDRINUSE`) - is because something is already using the port Node-RED is trying to use (`7882` in this case). The most likely explanation is the Node-RED instance is still running. But that is a very odd state to get into - the launcher should know if the node-red process it started previously is still running - and definitely shouldn't be trying to run it again if that's the case.

I haven't been able to reproduce this aspect of the issue. But I am testing this on MacOS - and given this is around low level process management, then this could be something specific to Windows we are not handling properly.

I'll ask @Steve-Mcl to do some investigation as he's just in the process of getting setup to develop and test FF on Windows.

---

I appreciate I'm posting this a week after you reported the issue, but the quick workaround would be to use Task Manager to identify the Node-RED process and manually kill it. That should free-up the port and let things run again - although without the Safe Mode option, the OPCUA node will crash it again.

**Comment by vdwpsmt** [comment]
Hi @knolleary, 
thanks for the info, very interesting to read, helps understanding the process.  And no worries about the delay, I'm only playing around with the platform, still side by side with the usual node-red instances.  Glad to see all of this progressing!

**Comment by Steve-Mcl** [comment]
Hi @vdwpsmt the issue is known to me. I actually encountered this yesterday evening but didn't raise an issue as I wanted to be sure it was a bug and not my setup. 

As you too are seeing this, in now convinced it is a Windows problem.

 The issue I witnessed was how  node spawns processes - the PID of the process is not the PID of the running node-red instance so cannot be stopped.  I will be continuing to investigate it today.

**Comment by Steve-Mcl** [comment]
For reference, I have published the branch [fix-win32-kill-and-status](https://github.com/flowforge/flowforge-nr-launcher/compare/fix-win32-kill-and-status)  at the request of @hardillb  ([changes can be viewed here](https://github.com/flowforge/flowforge-nr-launcher/commit/25e345ec574ba4aaef1dff8db9c3b22c3b3d3cf2))

The reason it is not a PR nor made it into the latest release is partly due to timing of nailing it down and because it will require testing on MAC and LINUX

For my windows box, running this version of code is now stable. Stopping and starting node-red.

### Explanation.
The launcher was firing up the standard `node-red.cmd` which in turn fires up nodejs and the node-red runtime `red.js` unfortunately, on windows, the PID of the process was for the shell NOT for the `node` process.  This left the node-red runtime active when requested to "stop" and thus the repeated logging of "address already in use" as flowforge attempted to launch another copy on the request of a "start".

### Thoughts.  
I wonder if there is any millage in exploring getting the PID of the process with port that node-red port (e.g. 7880) so as to avoid situations where flowforge/launcher has been terminated but the process is still running.  Same could be said of the launcher process?
