### ISSUE TITLE
Unable to create snapshots

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#658]
### Current Behavior

When I click "create snapshot" and submit the form, the systems seems to "Hang" and nothing happens.

### Expected Behavior

A snapshot is created, I get redirected to the index page of snapshots.

### Environment

- FlowForge version: staging server 2nd of June 2022
- Node.js version:
- npm version:
- Platform/OS: staging
- Browser: Chrome

**Comment by knolleary** [comment]
We can call the api for querying a project's snapshots on the staging env with the following url
```
https://[staging-env]/project/2393ee1c-ea37-4f86-828e-519dd994f4ef/snapshots
```

It is returning:

```
{
"statusCode": 500,
"error": "Internal Server Error",
"message": "column ProjectSnapshot.description does not exist"
}
```

This suggests the database migration to add this column hasn't applied properly. 

https://github.com/flowforge/flowforge/blob/main/forge/db/migrations/20220526-01-add-description-to-snapshots.js

It is working locally with the sqlite driver. Will need to test against a postgres backend to verify there's nothing untoward going on.

I think I need to look at the staging database to see what state it is in. The challenge today is I'm not immediately sure how to access to the staging database directly to do this sort of examination. First time for everything...

**Comment by knolleary** [comment]
I have identified a bug in one of the migrations - along with a better understanding of how that bug wasn't detected before now. This was partly due to most local testing happing with sqlite rather than postgres - but also a missed scenario in the testing.

I have not been able to access the staging database directly, but have added some admin-only api routes that let me examine the database and migration state. I can see what state staging has got into. The question is now how best to repair it. I think I have a way forward, but will pick it up tomorrow.

**Comment by knolleary** [comment]
Now fixed in staging.

Need to do some more testing to verify other behaviour, but I believe #661 has addressed the problem.

**Comment by knolleary** [comment]
Resolved in staging
