### ISSUE TITLE
Clicking Team Name should present dropdown list 

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#690]
### Current Behavior

The team selector on the main menu currently goes to the overview page if you click the name of the team, in order to switch teams you need to click the arrows.

It would be better if clicking the name had the same experience as the arrows (select team) as these all look to be one button.

In addition returning to the overview (current experience) isn't lost as the overview button is right beneath it.

### Expected Behavior

![image](https://user-images.githubusercontent.com/187645/173314897-59ab1fdd-55d8-495e-a4ba-16ee99b10be4.png)

### Environment

- FlowForge version: 0.6.0
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
Thanks for the interest @shikhar13012001 , you're most welcome to get involved.

The next step for this issue is some UX design work around this component as there are some related issues that need resolving (commenting from my phone here, so can't easily find the references - will add a comment with cross references in the morning).

As it stands, I'm not sure Sam's proposal is the right one given the role that component plays.

> In addition returning to the overview (current experience) isn't lost as the overview button is right beneath it.

This is not true when you are on a Project page - the team button is how you go back to the team.

We need to do the design work first that addresses the broader set of feedback, then we work on the implementation

**Comment by joepavitt** [comment]
Some crossover here with #646. We are looking to re-design the sidebar view when in a nested URL/hierarchy such as the Project view.

Current issues that exist:
- Back not obvious (#646)
- Team selection not obvious (#616)
- When viewing a project, not obvious you're in a nested vie, sidebar design is too similar to the "Team" view.

**Comment by knolleary** [comment]
I think this was resolved by #748 ?

**Comment by sammachin** [comment]
> 

Its not quite clear to me if the new dropdown uses the whole team name field or just the arrow from the screenshot in the PR

**Comment by knolleary** [comment]
Clicking anywhere in the box will open the team select dropdown - consistent with the user dropdown in the corner

<img width="533" alt="image" src="https://user-images.githubusercontent.com/51083/177338652-54a55dc2-7107-47e8-b045-1510be6b583a.png">

**Comment by joepavitt** [comment]
This has been resolved by #748 as per Nick's comment.
