### ISSUE TITLE
Limit max team size

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#781]
The license must set a limit on the maximum number of members in a team.
This is used in the CE to limit to the same size as the free team tier on Cloud Edition.

In EE licenses this would normally be set to the same value as the number of users on the platform making it moot but allows for other commercial models to be adopted with EE licensing too

**Comment by knolleary** [comment]
Examining this requirement some more, we have concluded that the max team size is *not* part of the license contents.

The platform will provide a predetermined set of Team Types (#733). The `starter` type is available to CE installations and will have a hardcoded limit of 3 members.

When we introduce the next tier of team type, its hardcoded limit will be 'unlimited'.

Having an EE license will determine whether this new team type is available or not.

**Comment by knolleary** [comment]
Currently the `starter` type has `userLimit` set to `0` because we didn't want to impose the limit pre 1.0.

The question is how to safely introduce this limit when there could be existing teams with >3 users already and we don't have the new team type available to upgrade to.

I think the most straightforward approach will be to modify the `userLimit` value in the database via a migration. We will not take any further action on teams that have > 3 members. They will not be able to add any new users, but everything else will continue to work.

**Comment by sammachin** [comment]
Looking at FF cloud currently we have one team of 7 (ours) one customer with a team of 4 and one with a team of 3 so grandfathering in these shouldn't be a problem

**Comment by knolleary** [comment]
The PR that closed this issue ensured the team userLimit is honoured by the platform APIs.

In the UI, if a user tries to add members that exceed that limit, they will get an error response from the API to say the limit has been reached. That isn't sufficient.

I am reopening this story as we need to get the UX right.
