### ISSUE TITLE
Import Credentials

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#835]
### Description

**As a:** user

**I want to:** import a credentials file from another Node-RED into my project

**So that:** I can migrate my projects to FlowForge more easily.

Need to decide what to do with existing credentials in the project, ideally they would be merged, although for MVP it would be viable to make this only available if a project does not already have any credentials.
Ideally this would be available from the project settings page at any time after a project has been created, but it could also be part of project creation.
The user should have a dialog to upload or paste a credentials file and then enter the credentials secret.
There should be validation of the secret as part of the import.

### Which customers would this be availble to

- [X] All Users, (CE)
- [ ] Specific Project Types (EE)
- [ ] Specific Team Tiers (EE)
- [ ] Other (See comments)

**Comment by knolleary** [comment]
There is a choice as to whether this is done in Node-RED or FlowForge.

Within Node-RED it would sit as part of the existing Import dialog.

If we do it at the FlowForge level, then I see it more a case of being able to import a Flow+Credential pair of files and have that replace the entire existing configuration rather than try to merge anything. I don't see the scenario where you already have the flows in Node-RED but want to just upload a different credentials file. This could be an implicit 'Import existing project' workflow - where that project is a flow/credential pair of files and a credSecret if needed.

**Comment by knolleary** [comment]
- Add to the 'Danger' settings page an option to 'import flows'.
 - Triggers dialog:

![Image](https://user-images.githubusercontent.com/51083/192796238-db4aa1ce-56a0-480f-91ee-9714eac61ef2.png)

 - Credentials file is optional
 - If credentials file provided and contents are determined to be encrypted, then show prompt for credential secret.

**Comment by hardillb** [comment]
Verified on Staging
