### ISSUE TITLE
Project Device List  - Deployed Snapshot

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#882]
### Current Behavior

In the Devices view of the project there is a column marked `Deployed Snapshot` but this shows the device name and ID, not a snapshot detail as shown at the top of the table

![image](https://user-images.githubusercontent.com/187645/184150988-d2e5abbc-89c7-48f5-9f10-886022bf1019.png)

### Expected Behavior

Show the deployed snapshot

### Steps To Reproduce

create project, assign device to project.

### Environment

- FlowForge version: 0.8.0
- Node.js version: 16.16
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
The new data table doesn't support nested objects in data rows in quite the way the old table did.

The code wants to pass the value of `activeSnapshot` to the `SnapshotComponent` - however the new data table doesn't know how to do that, so passes the top-level object, the device itself, to the component.

https://github.com/flowforge/flowforge/blob/main/frontend/src/pages/team/Devices/index.vue#L248

I hit this yesterday adding a new column to a different view, and raised https://github.com/flowforge/forge-ui-components/issues/43 on the data table to add support for this scenario.

The fix is to either wait for ui-components to fix that issue, then update the code here (to use `key` not `property`). Or even shorter-term is modify `SnapshotComponent` to use `{{activeSnapshot.name}}` and `{{activeSnapshot.id}}` (rather than `{{name}}` and `{{id}}`).

**Comment by knolleary** [comment]
Note this bug may be present in other uses of the table - I didn't spot the bad pattern in my original review, so I may have missed other cases.

**Comment by joepavitt** [comment]
I had spotted instances of this, and fixed them when I did the transition over to the new component. This _should_ be a one-off
