### ISSUE TITLE
Resolve `test:system` and `test:e2e` task duplication

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#886]
### Description

The recent work to introduce the end-to-end tests has introduced overlap between the existing `test:system` task and the newly added `test:e2e` task. They do exactly the same thing (`test:system` includes the necessary `--timeout` flag when used with postgres - so as it stands the `test:e2e` task will get false-positive failures when running with postgres).

We need to:

 - pick which name to use - `e2e` or `system`
 - update the tasks appropriately. We should have:
   - `test:XYZ` - runs both forge and frontend
   - `test:XYZ:forge`
   - `test:XYZ:frontend`
 - update the documentation: https://github.com/flowforge/flowforge/tree/main/docs/contribute#running-tests - they are out of date and don't mention any of the frontend testing.

I personally prefer `system` ... as its the name I picked originally for the system-wide type of testing and I don't see a reason to change it. But I won't stand in the way of progress if the consensus is something else.

**Comment by hardillb** [comment]
Only comment I would make is that we are currently only running the ui tests when the UI changes

**Comment by hardillb** [comment]
Ignore that last comment, I'd missed that `e2e` had sub types so we can still only call the UI tests when the UI has changed

**Comment by joepavitt** [comment]
This was fixed in https://github.com/flowforge/flowforge/commit/1cde38f9bd68f7a7c5cb78beba54dbaea226dca7#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 where the `test:e2e` and `test:e2e:frontend` were removed. They had both been added in my various iterations of trying tog et frontend E2E testing working, and ended up not needing them.

We use `test:system` to test server-side work, and no use `cy:run` (in conjunction with `cy:web-server` to test the frontend.
