### ISSUE TITLE
Setting UI doesn't allow me to update settings

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#911]
Cannot duplicate this project as there is no template to select for the new project.

### Current Behavior

![Screenshot 2022-08-23 at 15 11 56](https://user-images.githubusercontent.com/2529595/186167551-c8408c01-2b1d-4b94-92ee-a7b3b03a8287.png)

All settings are disabled. @joepavitt explained it's because of the template settings a user doesn't control.

### Expected Behavior

I can edit options shown

### Steps To Reproduce

Stats-gathering project in the FF team

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by joepavitt** [comment]
@sammachin a really good example of here of our recent discussion. All. options disabled for users, yet shown to them. Disabled because the underlying template forbids their editing.

Preferred UX Options:
- Don't show the settings at all if they're all disabled (i.e. don't overcomplicate/overwhelm users)
- Make it clearer in this view as to _why_ these options are disabled.
    - Another driver for https://github.com/flowforge/forge-ui-components/issues/27 
- Also grey out the text/interactive parts, as well as showing the locked icon, as I don't think it's obvious (at first glance) that these options are disabled/locked.

**Comment by sammachin** [comment]
In this case it looks like that project is using an old version of the template on FlowForge Cloud, where a number of the setting were locked. If you look at the fftools project that uses the latest template and the settings can be edited.

However I take you point that the UX could be better _when_ they are locked, For some fields eg timezone the value needs to be shown to the user even if they can't change it, there may be some where the whole field could be hidden if its not editable.

**Comment by sammachin** [comment]
Closing this as its related to that specific project being created on an old template

**Comment by ZJvandeWeg** [comment]
@sammachin Can you crosslink the issue then to migrate older projects to a current template? Otherwise nothing is fixed?

**Comment by sammachin** [comment]
Templates are not versioned they're just used at the point in time when a project is created. 
The fix for this project would be to duplicate it to a new project, however there seems to be something preventing that for this project as it won't let me select a template for the new project so I'm going to re-open this to track that bug

**Comment by hardillb** [comment]
I've checked the production database. There are only 2 projects in this state

 1. stats-gathering - owned by the flowforge team
 2. playground - owned by Nathaniel at Moment Factory.
 
It looks like we missed a DB migration at some point to add a default template to early projects.

Given there are only 2 projects (and we are on good terms with the owner of both teams) in this state I'm not convinced that this is worth any dev time to fix. Any new projects will have a template set.

If we really need to fix something on stats-gathering I can probably manually insert a template id into the database, but it's probably safer to just export the flow and recreate the project.

**Comment by ZJvandeWeg** [comment]
> If we really need to fix something on stats-gathering I can probably manually insert a template id into the database, but it's probably safer to just export the flow and recreate the project.

Ok, will do.

**Comment by sammachin** [comment]
I already spoke to Nat about the playground database when we discovered it
didn't have stacks either, he was happy to/going to delete it.

**Comment by hardillb** [comment]
@zj can we close this now? Your project should have been updated and we've talked to Nat.
