### ISSUE TITLE
Stack Label

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#915]
### Epic/Story

As an admin I want to give a stack a user friendly label that is displayed to users when selecting a stack, 

### Description

We are meant to be a low-code, low technical entry point tool, but as part of creating a project, a user must select a stack:

<img width="620" alt="Screenshot 2022-08-23 at 16 31 39" src="https://user-images.githubusercontent.com/99246719/186199832-777d8ed8-18ee-4fa6-beb7-98f4637b2225.png">

The no space formatting and lack of description looks too technical. We should have the option of a "nice"/formatted name for a given stack.

If I've selected a "Medium" project, I wouldn't expect to see `_Small`/`_Medium` at the end of the Stack name, simply `Node-RED v3.0.2` would suffice (with spacing).

**Comment by sammachin** [comment]
Part of the issue here is that stacks only have one field the Name which has to be globally unique, but a stack incorporates elements that are displayed to the user in the project type, eg the CPU/Memory.
We need a label field that is displayed to the user and does not have to be unique across the platform, this field should support whitespace and other special characters.

**Comment by hardillb** [comment]
Live on Staging, all looks like I intended, but just noticed that the Admin Stack table doesn't show the label.

**Comment by hardillb** [comment]
Going to say this is done, but open https://github.com/flowforge/flowforge/issues/1137 to track

**Comment by ZJvandeWeg** [comment]
@hardillb Should this issue be closed now?
