### ISSUE TITLE
Coupon Codes in Signup Links

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#978]
### Description

**As a:** user

**I want to:** be able to embed the coupon code in the signup URL and have that auto-populate/apply the coupon code at the stripe checkout

**So that:** I can make better use of coupon code

### Acceptance Criteria

- [ ] Signup URL can contain a query param eg `/signup?coupon=SOMECODE`
- [ ] This is persisted (cookie?) through the users signup journey and when they are redirected to the Stripe checkout sesison the coupon is passed in the call to stripe.
- [ ] Coupon is automatically applied to the subscription
- ...

**Comment by hardillb** [comment]
@sammachin do you have a link to the stripe docs about passing a coupon (save me hunting for it)

**Comment by sammachin** [comment]
Its an array called `discounts` in https://stripe.com/docs/api/checkout/sessions/create

**Comment by sammachin** [comment]
It takes either `promotion_code` or `coupon` The former being the public facing code and the coupon being an internal reference, we should use `promotion_code` as this allows better tracking

**Comment by hardillb** [comment]
@sammachin Thanks.

I'm trying to work out where to hang the entry route.

Because it's billing related it should be in the `ee` code, which would give it a route like `/ee/billing/signup`

Just to be clear on scope here, this is purely for new users?
What should happen if an existing (logged in) user follows the signup link?
