### ISSUE TITLE
Core Nodes - TCP/UDP

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#999]
### Description

Using these epics to explore options for users around the core nodes that are disabled in FlowForge Cloud.

The TCP and UDP nodes are disabled in FlowForge Cloud,

This is because the container networking does not permit inbound connections to arbitrary ports.

There is a limitation in Node-RED in that a single node is used for both inbound and outbound connections, Outbound technically will work from FlowForge Cloud. 

Additionally users want to utilise these nodes when deploying to devices both for inbound and outbound connections.

Possible solutions may include: 
An upstream change to the nodes in node-red to split or control the inbound/outbound behaviour separately, 
Allowing inbound ports to cloud containers - would need significant R&D work
Some kind of stub/warning to users if they run the nodes in the cloud.

**Comment by sammachin** [comment]
Following discussion the intention is to make changes upstream in Node-RED such that the TCP and UDP nodes can then detect if the host platform allows inbound network connection and only show that option in the config if so.
This would then allow us to enable these nodes in FF cloud with a good user experience.

Where users may want to handle inbound TCP/UDP connections on a device this would be served by the work in #1012 to allow on device editing using these nodes with all their settings.

**Comment by sammachin** [comment]
Keeping epic open to reference the upstream work

**Comment by knolleary** [comment]
Upstream issue raised: https://github.com/node-red/node-red/issues/3902

**Comment by Steve-Mcl** [comment]
Following discussion, this work was put aside until further though is given.
Points of consideration...
1. since a new stack will need to be generated when NR 3.1 is released, this work is not necessary at this point in time
2. When introducing this, we may need to consider the stack version (or rather the node-red version) since allowing UDP/TCP nodes to be installed at the platform level but disabling incoming connections is NR V3.1+ only
3. Ben considers these "new settings" (tcp/udp server allow) should be part of the stack or template (not the platform)

**Comment by ZJvandeWeg** [comment]
@Steve-Mcl @knolleary If there's work to be done around 1.4, should this issue be closed? Or reopened and put back into the backlog?
